---
- name: 'Generate "POST-SETUP" tasks file from template (1/4): >> Checks'
  template:
    src: "{{ role_path }}/tasks/templates/checks.yml.j2"
    dest: "{{ role_path }}/temp/03_1_{{ role_name }}__post-setup_checks.yml"
  vars:
    label: "[POST-SETUP]"
    checks: "{{ post_setup.checks | default([]) }}"
    #post_setup_checks: "{{ post_setup | default([]) }}"
  delegate_to: localhost
  changed_when: false

- name: 'Generate "POST-SETUP" tasks file from template (2/4): >> Installations'
  template:
    src: "{{ role_path }}/tasks/templates/installations.yml.j2"
    dest: "{{ role_path }}/temp/03_2_{{ role_name }}__post-setup_installations.yml"
  vars:
    label: "[POST-SETUP]"
    components: "{{ post_setup.installations.software_components | default([]) }}"
    #install_items: "{{ post_setup.installations | default([]) }}"
  delegate_to: localhost
  changed_when: false

- name: 'Generate "POST-SETUP" tasks file from template (3/4): >> Configurations'
  template:
    src: "{{ role_path }}/tasks/templates/configurations.yml.j2"
    dest: "{{ role_path }}/temp/03_3_{{ role_name }}__post-setup_configurations.yml"
  vars:
    label: "[POST-SETUP]"
    configs: "{{ post_setup.configurations | default([]) }}"
  delegate_to: localhost
  changed_when: false

- name: 'Generate "POST-SETUP" tasks file from template (4/4): >> Executions'
  template:
    src: "{{ role_path }}/tasks/templates/executions.yml.j2"
    dest: "{{ role_path }}/temp/03_4_{{ role_name }}__post-setup_executions.yml"
  vars:
    label: "[POST-SETUP]"
    execs: "{{ post_setup.executions | default([]) }}"
  delegate_to: localhost
  changed_when: false