---

all:
  children:
    # WinRM over HTTP (port 5985)
    winrm_http:
      hosts:
        win2019-http:
          ansible_host: 192.168.56.12
          ansible_port: 5985
          ansible_winrm_scheme: http

    # WinRM over HTTPS (port 5986)
    winrm_https:
      hosts:
        win2019-https:
          ansible_host: 192.168.56.12
          ansible_port: 5986
          ansible_winrm_scheme: https

    # Backup Hosts
    backup_hosts:
      hosts:
        backup-host1:
          ansible_host: 192.168.11.111
          ansible_port: 5985
          ansible_winrm_scheme: http
          #ansible_user: Administrator
          #ansible_password: aminetest

  vars:
    ansible_user: Administrator
    ansible_password: aminetest
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    pkgs_repo_base_url: "http://simulated-artifactory.local/artifactory/ansible-win-auto-prov-artifacts"
    http_auth_username: "repouser"
    http_auth_password: "repopassword"
    win_temp_dir_path: 'C:\AWAP_Temp'
    uploads_dir: '../uploads'
    templates_dir: '../templates'
    root_install_dir: 'D:\AppServ'
