all:
  hosts:
    192.168.66.12:
  vars:
    ansible_user: Administrator
    ansible_password: pwdAdmin2023
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    pkgs_repo_base_url: "https://simulated-artifactory.local/artifactory/ansible-win-auto-prov-artifacts"
    http_auth_username: "artifactuser"
    http_auth_password: "pwdUsr23"
    win_temp_dir_path: 'C:\AWAP_Temp'
    uploads_dir: '../uploads' # Path either full or related to where playbook's main file is located
    templates_dir: '../templates'
    root_install_dir: D:\AppServ