---
- name: 'Generate "SETUP" tasks file from template (1/4): >> Checks'
  template:
    src: "{{ role_path }}/tasks/templates/checks.yml.j2"
    dest: "{{ role_path }}/temp/02_1_{{ role_name }}__setup_checks.yml"
  vars:
    label: "[SETUP]"
    checks: "{{ setup.checks | default([]) }}"
  delegate_to: localhost
  changed_when: false

- name: 'Generate "SETUP" tasks file from template (2/4): >> Installations'
  template:
    src: "{{ role_path }}/tasks/templates/installations.yml.j2"
    dest: "{{ role_path }}/temp/02_2_{{ role_name }}__setup_installations.yml"
  vars:
    label: "[SETUP]"
    components: "{{ setup.installations.software_components | default([]) }}"
    #install_items: "{{ setup.installations | default([]) }}"
  delegate_to: localhost
  changed_when: false

- name: 'Generate "SETUP" tasks file from template (3/4): >> Configurations'
  template:
    src: "{{ role_path }}/tasks/templates/configurations.yml.j2"
    dest: "{{ role_path }}/temp/02_3_{{ role_name }}__setup_configurations.yml"
  vars:
    label: "[SETUP]"
    configs: "{{ setup.configurations | default([]) }}"
  delegate_to: localhost
  changed_when: false

- name: 'Generate "SETUP" tasks file from template (4/4): >> Executions'
  template:
    src: "{{ role_path }}/tasks/templates/executions.yml.j2"
    dest: "{{ role_path }}/temp/02_4_{{ role_name }}__setup_executions.yml"
  vars:
    label: "[SETUP]"
    execs: "{{ setup.executions | default([]) }}"
  delegate_to: localhost
  changed_when: false