---
- name: "Start operations.."
  meta: noop


- name: "Initialization.."
  win_file:
    path: '{{ win_temp_dir_path }}'
    state: directory


      
              

 

- name: "[POST-SETUP] (1/1) Run user-provided script (Install 'Prettier' and 'Material Icons' extensions)"
  win_shell: |
    try {
      code --extensions-dir "D:\AppServ\VSCode\resources\app\extensions" --install-extension "C:\AWAP_Temp\PKief.material-icon-theme-4.28.0.vsix" --force
      code --extensions-dir "D:\AppServ\VSCode\resources\app\extensions" --install-extension "C:\AWAP_Temp\esbenp.prettier-vscode-9.16.0.vsix" --force
    } catch {
        $errorMessage = $_.Exception.Message
        Write-Host "Unexpected exception/error: $errorMessage"
        exit 1
    }

  register: script_result
  changed_when: script_result.rc == 0 and 'OK_CHANGE' in script_result.stdout
  failed_when: script_result.rc != 0 or 'KO_FAILURE' in script_result.stdout
  ignore_errors: yes    
              
          


  