---
- name: "Include role's tasks"
  block:
    - include_tasks: 01_pre-setup.yml
    - include_tasks: "{{ role_path }}/temp/01_{{ role_name }}__pre-setup.yml"
    - include_tasks: 02_setup.yml
    - include_tasks: "{{ role_path }}/temp/02_{{ role_name }}__setup.yml"
    - include_tasks: 03_post-setup.yml
    - include_tasks: "{{ role_path }}/temp/03_{{ role_name }}__post-setup.yml"
  #ignore_errors: yes

