---
- name: "Start operations.."
  meta: noop


- name: "Initialization.."
  win_file:
    path: '{{ win_temp_dir_path }}'
    state: directory


                    

- name: "[SETUP] (1/1) Check 'python3' status *BEFORE* installation"
  win_shell: |
    $appName = "python3"
    $wmiQuery = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*$appName*" }
    $regPath1 = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall"
    $regPath2 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
    $regCheck1 = Get-ChildItem -Path $regPath1 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    $regCheck2 = Get-ChildItem -Path $regPath2 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    if ($wmiQuery -or $regCheck1 -or $regCheck2) { $status = "Installed" } else { $status = "Not Installed" }
    Write-Host "$appName is $status"
  register: initial_software_status
  changed_when: false
  no_log: true

- name: "[SETUP] (1/1) Check if HTTP authentication is required for file download"
  win_shell: |
    $url = "{{ pkgs_repo_base_url }}/python/python-3.12.0-amd64.exe"
    $responseStatusCode = $(try { Invoke-WebRequest -Uri $url -Method Head -UseBasicParsing | % {$_.StatusCode} } catch {$_.Exception.Response.StatusCode.Value__})

    if ($responseStatusCode -eq 401) { 
        Write-Host "Auth required" 
    } else { 
        Write-Host "Auth not required" 
    }
  register: auth_check
  changed_when: false
  no_log: true
  when: "'Not Installed' in initial_software_status.stdout"


- name: "[SETUP] (1/1) Download 'python3' files (with authentication)"
  win_get_url:
    url: "{{ pkgs_repo_base_url }}/python/python-3.12.0-amd64.exe"
    dest: '{{ win_temp_dir_path }}\python-3.12.0-amd64.exe'
    username: "{{ http_auth_username }}"
    password: "{{ http_auth_password }}"
  when: "'Not Installed' in initial_software_status.stdout and 'Auth required' in auth_check.stdout"


- name: "[SETUP] (1/1) Download 'python3' files (without authentication)"
  win_get_url:
    url: "{{ pkgs_repo_base_url }}/python/python-3.12.0-amd64.exe"
    dest: '{{ win_temp_dir_path }}\python-3.12.0-amd64.exe'
  when: "'Not Installed' in initial_software_status.stdout and 'Auth not required' in auth_check.stdout"

 


  


- name: "[SETUP] (1/1) Check custom target installation directory"
  win_file:
    path: 'D:\AppServ'
    state: directory
  when: "'Not Installed' in initial_software_status.stdout"




- name: "[SETUP] (1/1) Install 'python3'"
  win_shell: |
    $installResult = $null
    $installSuccess = $false

     try {
      $installResult = (Start-Process -FilePath "{{ win_temp_dir_path }}\python-3.12.0-amd64.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=0 TargetDir=D:\AppServ\python3 Shortcuts=1 Include_symbols=1 Include_debug=1" -Wait -PassThru).ExitCode

 
      $installResult = 0
    } catch {
      $errorMessage = $_.Exception.Message
      Write-Host "ERROR: $errorMessage"
      $installResult = 1
    }
        # "0" as exit success code; typically for common installers like NSIS
    if ($installResult -eq 0) {$installSuccess = $true}


    if (-not $installSuccess) {
        Write-Output "python3 installation failed. Exit Code: $installResult"
        exit 1 }
  register: component_install_result
  failed_when: component_install_result.rc != 0 or 'installation failed' in component_install_result.stdout
  when: "'Not Installed' in initial_software_status.stdout"


- name: "[SETUP] (1/1) Check 'python3' status *AFTER* installation"
  win_shell: |
    $appName = "python3"
    $wmiQuery = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*$appName*" }
    $regPath1 = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall"
    $regPath2 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
    $regPath3 = "HKLM:\SOFTWARE"
    $regCheck1 = Get-ChildItem -Path $regPath1 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    $regCheck2 = Get-ChildItem -Path $regPath2 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    $regCheck3 = Get-ChildItem -Path $regPath3 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    if ($wmiQuery -or $regCheck1 -or $regCheck2 -or $regCheck3) { $status = "Installed" } else { $status = "Not Installed" }
    Write-Host "$appName is $status"
  register: new_software_status
  changed_when: false
  failed_when: new_software_status.rc != 0 or 'Not Installed' in new_software_status.stdout
  ignore_errors: yes  
  when: "'Not Installed' in initial_software_status.stdout"

                  







  