---
# Playbook: Setup Core Software Bundle

- name: Setup Notepad++
  hosts: all
  gather_facts: no
  tags: notepadpp
  roles:
    - role: setup-notepadpp
      vars:
        install:
          components:
            - software_fullname: "Notepad++"
              installer_relative_path: notepadpp/npp.8.5.4.Installer.x64.exe
              type: exe
              arguments: "/S"


- name: Setup 7-Zip
  hosts: all
  gather_facts: no
  tags: 7zip
  roles:
    - role: setup-7zip
      vars:
        install:
          components:
            - software_fullname: "7-Zip"
              installer_relative_path: 7zip/7z2301-x64.msi
              type: msi
              arguments: ""


- name: Setup OpenSSL
  hosts: all
  gather_facts: no
  tags: openssl
  roles:
    - role: setup-openssl
      vars:
        preinstall:
          components:
            - software_fullname: "Microsoft Visual C++ 2022 X64"
              installer_relative_path: ms-vc-redist/VC_redist.x64_15-17-19-22.exe
              type: exe
              arguments: "/q /norestart" 
        install:
          components:
            - software_fullname: "OpenSSL"
              installer_relative_path: openssl/Win64OpenSSL_Light-3_1_2.msi
              type: msi
              arguments: "" # for 'msi' type, 'arguments' string should always be empty / or better: ignore it
        postinstall:
          configurations:
            - resource_type: path_envvar # [reg, envvar] 
              resource_name: PATH # should be ignored in case of 'path_envvar'
              value: 'C:\Program Files\OpenSSL-Win64\bin' # /!\ use single quotes ('value_for_resource')
              action_type: append # [create, modify, delete, check]


- name: Setup KeePass
  hosts: all
  gather_facts: no
  tags: keepass
  roles:
    - role: setup-keepass
      vars:
        install:
          components:
            - software_fullname: "KeePass"
              installer_relative_path: keepass/KeePass-2.54.msi
              type: msi
              arguments: ""


- name: Setup Firefox
  hosts: all
  gather_facts: no
  tags: firefox
  roles:
    - role: setup-firefox
      vars:
        install:
          components:
            - software_fullname: "Firefox"
              installer_relative_path: firefox/FirefoxSetup114.0.2.msi
              type: msi
              arguments: ""


- name: Setup Draw.io
  hosts: all
  gather_facts: no
  tags: drawio
  roles:
    - role: setup-drawio
      vars:
        install:
          components:
            - software_fullname: "draw.io"
              installer_relative_path: draw-io/draw.io-21.6.8-windows-installer.exe
              type: exe
              arguments: "/allusers /S"


- name: Setup Pandoc
  hosts: all
  gather_facts: no
  tags: pandoc
  roles:
    - role: setup-pandoc
      vars:
        install:
          components:
            - software_fullname: "Pandoc"
              installer_relative_path: pandoc/pandoc-3.1.3-windows-x86_64.msi
              type: msi
              arguments: ""


- name: Setup BeyondCompare
  hosts: all
  gather_facts: no
  tags: beyondcompare
  roles:
    - role: setup-beyondcompare
      vars:
        install:
          components:
            - software_fullname: "Beyond Compare"
              installer_relative_path: beyond-compare/BCompare-4.4.6.27483_x64.msi
              type: msi
              arguments: ""


- name: Setup Adobe PDF Reader
  hosts: all
  gather_facts: no
  tags: adobereader
  roles:
    - role: setup-adobereader
      vars:
        install:
          components:
            - software_fullname: "Adobe Acrobat Reader"
              installer_relative_path: adobe-reader/AcroRdrDC2300320201_en_US.exe
              type: exe
              arguments: "/sAll /rs /msi /norestart EULA_ACCEPT=YES"


- name: Setup Greenshot
  hosts: all
  gather_facts: no
  tags: greenshot
  roles:
    - role: setup-greenshot
      vars:
        install:
          components:
            - software_fullname: "Greenshot"
              installer_relative_path: greenshot/Greenshot-INSTALLER-1.2.10.6-RELEASE.exe
              type: exe
              arguments: "/VERYSILENT /NORESTART"