---
- name: "Start operations.."
  meta: noop


- name: "Initialization.."
  win_file:
    path: '{{ win_temp_dir_path }}'
    state: directory


                    

- name: "[SETUP] (1/1) Check 'Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)' status *BEFORE* installation"
  win_shell: |
    $appName = "Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)"
    $wmiQuery = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*$appName*" }
    $regPath1 = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall"
    $regPath2 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
    $regCheck1 = Get-ChildItem -Path $regPath1 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    $regCheck2 = Get-ChildItem -Path $regPath2 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    if ($wmiQuery -or $regCheck1 -or $regCheck2) { $status = "Installed" } else { $status = "Not Installed" }
    Write-Host "$appName is $status"
  register: initial_software_status
  changed_when: false
  no_log: true

- name: "[SETUP] (1/1) Check if HTTP authentication is required for file download"
  win_shell: |
    $url = "{{ pkgs_repo_base_url }}/eclipse_temurin_openjdk/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi"
    $responseStatusCode = $(try { Invoke-WebRequest -Uri $url -Method Head -UseBasicParsing | % {$_.StatusCode} } catch {$_.Exception.Response.StatusCode.Value__})

    if ($responseStatusCode -eq 401) { 
        Write-Host "Auth required" 
    } else { 
        Write-Host "Auth not required" 
    }
  register: auth_check
  changed_when: false
  no_log: true
  when: "'Not Installed' in initial_software_status.stdout"


- name: "[SETUP] (1/1) Download 'Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)' files (with authentication)"
  win_get_url:
    url: "{{ pkgs_repo_base_url }}/eclipse_temurin_openjdk/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi"
    dest: '{{ win_temp_dir_path }}\OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi'
    username: "{{ http_auth_username }}"
    password: "{{ http_auth_password }}"
  when: "'Not Installed' in initial_software_status.stdout and 'Auth required' in auth_check.stdout"


- name: "[SETUP] (1/1) Download 'Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)' files (without authentication)"
  win_get_url:
    url: "{{ pkgs_repo_base_url }}/eclipse_temurin_openjdk/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi"
    dest: '{{ win_temp_dir_path }}\OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi'
  when: "'Not Installed' in initial_software_status.stdout and 'Auth not required' in auth_check.stdout"

 


  


- name: "[SETUP] (1/1) Check custom target installation directory"
  win_file:
    path: 'D:\AppServ\Java'
    state: directory
  when: "'Not Installed' in initial_software_status.stdout"




- name: "[SETUP] (1/1) Install 'Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)'"
  win_shell: |
    $installResult = $null
    $installSuccess = $false

    $installResult = (Start-Process -FilePath "msiexec.exe" -ArgumentList "/i `"{{ win_temp_dir_path }}\OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi`" INSTALLDIR=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" TARGETDIR=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" INSTALLLOCATION=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" INSTALLFOLDER=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" INSTALLPATH=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" APPLICATIONFOLDER=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" APPDIR=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" ARPINSTALLLOCATION=`"D:\AppServ\Java\Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)`" /qn" -Wait -PassThru).ExitCode
    if ($installResult -eq 0) {$installSuccess = $true}


    if (-not $installSuccess) {
        Write-Output "Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64) installation failed. Exit Code: $installResult"
        exit 1 }
  register: component_install_result
  failed_when: component_install_result.rc != 0 or 'installation failed' in component_install_result.stdout
  when: "'Not Installed' in initial_software_status.stdout"


- name: "[SETUP] (1/1) Check 'Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)' status *AFTER* installation"
  win_shell: |
    $appName = "Eclipse Temurin JDK with Hotspot 11.0.20.1+1 (x64)"
    $wmiQuery = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*$appName*" }
    $regPath1 = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall"
    $regPath2 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
    $regPath3 = "HKLM:\SOFTWARE"
    $regCheck1 = Get-ChildItem -Path $regPath1 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    $regCheck2 = Get-ChildItem -Path $regPath2 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    $regCheck3 = Get-ChildItem -Path $regPath3 | Where-Object { $_.GetValue("DisplayName") -like "*$appName*" }
    if ($wmiQuery -or $regCheck1 -or $regCheck2 -or $regCheck3) { $status = "Installed" } else { $status = "Not Installed" }
    Write-Host "$appName is $status"
  register: new_software_status
  changed_when: false
  failed_when: new_software_status.rc != 0 or 'Not Installed' in new_software_status.stdout
  ignore_errors: no  
  when: "'Not Installed' in initial_software_status.stdout"

                  







  