---
- name: 'Generate "POST-SETUP" tasks file from template'
  template:
    src: "{{ role_path }}/tasks/templates/operations.yml.j2"
    dest: "{{ role_path }}/temp/03_{{ role_name }}__post-setup.yml"
  vars:
    label: "[POST-SETUP]"
    setup_phase: post_setup
    setup_phase_operations: "{{ post_setup | default([]) }}"
  delegate_to: localhost
  changed_when: false