---
- name: "Clear '{{ role_name }}' role temp. dir. (1/2)"
  find:
    paths: '{{ role_path }}/temp/'
    patterns: '*'
    recurse: yes
  delegate_to: localhost
  register: temp_contents
  changed_when: false
  no_log: true

- name: "Clear '{{ role_name }}' role temp. dir. (2/2)"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ temp_contents.files }}"
  when: temp_contents.matched > 0
  delegate_to: localhost
  changed_when: false
  no_log: true

- name: "Include '{{ role_name }}' role's tasks"
  block:
    - include_tasks: 01_pre-setup.yml
    - include_tasks: "{{ role_path }}/temp/01_{{ shortname | default('') }}__pre-setup.yml"
    - include_tasks: 02_setup.yml
    - include_tasks: "{{ role_path }}/temp/02_{{ shortname | default('') }}__setup.yml"
    - include_tasks: 03_post-setup.yml
    - include_tasks: "{{ role_path }}/temp/03_{{ shortname | default('') }}__post-setup.yml"
  #ignore_errors: yes

