---

- name: Setup Node.JS v14, v16 and v18
  hosts: all
  gather_facts: no
  tags: nodejs
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: nodejs
        setup:
          - installations:
            - software_components:
              - software_fullname: "NodeJS v14.17.3" 
                file_relative_url: nodejs/node-v14.17.3-win-x64.zip
                type: zip
                root_install_dir: D:\AppServ\nodejs
                desktop_shortcut: no # Default: no
                startmenu_shortcut: no # Default: yes

              - software_fullname: "NodeJS v16.16.0" 
                file_relative_url: nodejs/node-v16.16.0-win-x64.zip
                type: zip
                root_install_dir: D:\AppServ\nodejs
                desktop_shortcut: no # Default: no
                startmenu_shortcut: no # Default: yes

              - software_fullname: "NodeJS v18.18.0" 
                file_relative_url: nodejs/node-v18.18.0-win-x64.zip
                type: zip
                root_install_dir: D:\AppServ\nodejs
                desktop_shortcut: no # Default: no
                startmenu_shortcut: no # Default: yes

        post_setup:
          - configurations:
            - update_resource:
              - resource_type: file_system
                operation_type: transfer
                source:
                  upload_file: bundles/basic_win/setup-nodejs/check_NODEJS_HOME.ps1
                destination: C:\opt\ScriptPS\Starter\startup_scripts\

              - resource_type: file_system
                operation_type: transfer
                source:
                  upload_file: bundles/basic_win/setup-nodejs/set_NODEJS_HOME.ps1
                destination: D:\AppServ\NodeJS\

              - resource_type: file_system
                operation_type: shortcut
                source: '%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe'
                arguments: '-WindowStyle Hidden -ExecutionPolicy Bypass -File "D:\AppServ\nodejs\set_NODEJS_HOME.ps1"'
                destination: '%PUBLIC%\Desktop\Set Runtime Versions\Set NodeJs Version.lnk'
                icon: D:\AppServ\nodejs\NodeJS v18.18.0\node-v18.18.0-win-x64\node.exe,0

  #tasks:
  #  - name: '[POST-SETUP] {NODEJS} Notify logged in users with a message'
  #    community.windows.win_msg:
  #      display_seconds: 259200
  #      msg: "** SYSTEM ADMIN ** \n\nNode.JS configurations updated. Please, save your work and log off (sign out) to enable them."
  #    changed_when: false
  #    no_log: yes


- name: "Setup Eclipse IDE for JEE: 2022-12, 2020-06, Oxygen (2017-06) and Neon 3 (2016-06)"
  hosts: all
  gather_facts: no
  tags: eclipseide
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: eclipseide
        setup:
          - installations:
            - software_components:
              - software_fullname: "Eclipse IDE 2020-06" 
                file_relative_url: eclipse_jee_ide/eclipse-jee-2020-06-R-win32-x86_64.zip
                type: zip
                root_install_dir: D:\AppServ
                main_app_launcher: eclipse\eclipse.exe
                desktop_shortcut: yes # Default: no
                shortcut_name: 'Eclipse IDEs\Eclipse 2020-06' # Default shortcut name == 'software_fullname'
                startmenu_shortcut: yes # Default: yes
                #
              - software_fullname: "Eclipse IDE 2022-12" 
                file_relative_url: eclipse_jee_ide/eclipse-jee-2022-12-R-win32-x86_64.zip
                type: zip
                root_install_dir: D:\AppServ
                main_app_launcher: eclipse\eclipse.exe
                desktop_shortcut: yes # Default: no
                shortcut_name: 'Eclipse IDEs\Eclipse IDE 2022-12'
                startmenu_shortcut: yes # Default: yes
                #
              - software_fullname: "Eclipse IDE Neon 3 (2016-06)" 
                file_relative_url: eclipse_jee_ide/eclipse-jee-neon-3-win32-x86_64.zip
                type: zip
                root_install_dir: D:\AppServ
                main_app_launcher: eclipse\eclipse.exe
                desktop_shortcut: yes # Default: no
                shortcut_name: 'Eclipse IDEs\Eclipse IDE Neon 3 (2016-06)'
                startmenu_shortcut: yes # Default: yes
                #
              - software_fullname: "Eclipse IDE Oxygen (2017-06)" 
                file_relative_url: eclipse_jee_ide/eclipse-jee-oxygen-R-win32-x86_64.zip
                type: zip
                root_install_dir: D:\AppServ
                main_app_launcher: eclipse\eclipse.exe
                desktop_shortcut: yes # Default: no
                shortcut_name: 'Eclipse IDEs\Eclipse IDE Oxygen (2017-06)'
                startmenu_shortcut: yes # Default: yes
              

- name: Setup Cygwin x64
  hosts: all
  gather_facts: no
  tags: cygwin
  roles:
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: cygwin
        setup:
          - configurations:
            - update_resource:  
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: cygwin/cygwin64install_cyg_v3_4_9.zip
                destination: D:\AppServ\Cygwin\
                unzip: yes # Default: 'no'
                force_overwrite_dest: no # Default: yes # Ignored when unzip == 'no'
          - installations:
            - software_components:
              - software_fullname: Cygwin
                file_relative_url: cygwin/cygwin_v3_4_9_setup-x86_64.exe
                type: exe
                arguments: --quiet-mode --local-install --local-package-dir D:\AppServ\Cygwin\cygwin64install --root D:\AppServ\Cygwin\cygwin64 --no-shortcuts --packages libpopt-common,terminfo,tzdata,cygwin-devel,w32api-headers,windows-default-manifest,libsource-highlight-common,publicsuffix-list-dafsa,libgsasl-common,gsettings-desktop-schemas,cygwin,libiconv2,libintl8,w32api-runtime,libintl-devel,libncursesw10,libreadline7,bash,libzstd1,crypto-policies,base-cygwin,zlib0,libpng16,libgpg-error0,libpcre1,libidn12,libjbig2,libdeflate0,libXdmcp6,libXau6,libwebp7,liblcms2_2,libbrotlicommon1,libnghttp2_14,libidn2_0,libntlm0,libkrb5support0,libedit0,cygrunsrv,libpkgconf4,libsqlite3_0,m4,libatomic1,libiconv,gettext,libxxhash0,libexpat1,libcrypt2,libltdl7,libffi8,libunistring5,which,vim-minimal,tzcode,sed,run,ncurses,mintty,login,libtasn1_6,libsmartcols1,libsigsegv2,libpopt0,libpipeline1,libpcre2_8_0,liblzma5,liblz4_1,libgmp10,libgcc1,libffi6,libbz2_1,libattr1,libargp,ipc-utils,hostname,gzip,editrights,diffutils,dash,binutils,alternatives,libgcrypt20,libxcb1,libwebpmux3,libwebpdemux2,libbrotlidec1,libk5crypto3,pkgconf,libtool,libpsl5,cygutils,less,grep,libxml2,xz,libisl23,libjpeg8,libcom_err2,libquadmath0,libgomp1,perl_base,libgc1,libuuid1,libstdc++6,libmpfr6,libgdbm6,libp11-kit0,file,bzip2,coreutils,getent,rebase,info,_autorebase,libfreetype6,pkg-config,libglib2.0_0,desktop-file-utils,libkrb5_3,libimagequant0,libguile3.0_1,libblkid1,libgraphite2_3,libtiff6,libdb5.3,libicu61,libncurses++w10,zstd,libuchardet0,libmpc3,gawk,libgdbm_compat4,p11-kit-trust,p11-kit,findutils,gamin,libfam0,libgssapi_krb5_2,make,libfdisk1,libboost_regex1.66,libncurses-devel,tar,groff,gcc-core,csih,perl,ca-certificates,base-files,shared-mime-info,libgsasl18,util-linux,libsource-highlight4,gcc-g++,autoconf2.1,perl-JSON-PP,libssl3,libssl1.1,libharfbuzz0,libfribidi0,man-db,perl_autorebase,openssl,libsasl2_3,libssh2_1,libfido2,python39,python39-platformdirs,python39-setuptools,rsync,libraqm0,autoconf2.7,autoconf2.5,texinfo,perl-TermReadKey,perl-Error,libopenldap2,openssh,python39-iniconfig,python39-six,python39-idna,python39-toml,python39-pluggy,python39-babel,python39-markupsafe,python39-snowballstemmer,python39-imagesize,python39-olefile,python39-chardet,autoconf,libopenldap2_4_2,libcurl4,python39-urllib3,python39-jinja2,automake1.9,automake1.16,automake1.13,automake1.12,automake1.11,automake1.10,automake1.14,automake1.15,git,python39-requests,python39-pyparsing,automake,python39-packaging,python39-pytest,python39-imaging,python39-pygments,python39-docutils,python39-sphinx,python39-pip,python39-sphinxcontrib-serializinghtml,python3,gdb,gettext-devel,libsodium-common,xxd,libsodium23,vim-common,vim
                manual_registration:
                  root_install_dir: D:\AppServ
                  main_app_launcher: cygwin64\bin\mintty.exe
                  desktop_shortcut: yes
                  startmenu_shortcut: yes
                  shortcut_arguments: '-i /Cygwin-Terminal.ico -'
                  shortcut_icon: D:\AppServ\Cygwin\cygwin64\Cygwin.ico  # Provide full path, optionnally followed with icon index, e.g. 'filpath,12'
                #abort_on_aftercheck_failure: no # Default: yes


- name: "Setup DBeaver"
  hosts: all
  gather_facts: no
  tags: dbeaver
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: dbeaver
        setup:
          - installations:
            - software_components:
              - software_fullname: "DBeaver"
                file_relative_url: dbeaver/dbeaver-ce-23.2.1-x86_64-setup.exe
                type: exe
                arguments: /allusers /S /D=D:\AppServ\DBeaver


- name: "Setup Git Extensions"
  hosts: all
  gather_facts: no
  tags: gitextensions
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: gitextensions
        pre_setup:
          - installations:
            - software_components:
              - software_fullname: Microsoft Windows Desktop Runtime
                file_relative_url: ms-dotnet/windowsdesktop-runtime-6.0.24-win-x64.exe
                type: exe
                arguments: /install /quiet /norestart
              - software_fullname: Git
                file_relative_url: git/Git-2.42.0.2-64-bit.exe
                type: exe
                arguments: /DIR=D:\AppServ\Git /VERYSILENT /NORESTART /COMPONENTS=icons,icons\desktop,ext,ext\shellhere,ext\guihere,gitlfs,assoc,assoc_sh
              - software_fullname: "kdiff3"
                file_relative_url: kdiff3/kdiff3-1.10.5-windows-x86_64.exe
                type: exe
                arguments: /S /D=D:\AppServ\KDiff3
        setup:
          - installations:
            - software_components:
              - software_fullname: Git Extensions
                file_relative_url: gitextensions/GitExtensions-4.1.0.16698-1fe52a137.msi
                type: msi
                root_install_dir: D:\AppServ


- name: "Setup UML Designer"
  hosts: all
  gather_facts: no
  tags: umldesigner
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: umldesigner
        setup:
          - installations:
            - software_components:
              - software_fullname: "UMLDesigner" # /!\ Attention when 'create_directory' is set to 'no' /!\
                file_relative_url: umldesigner/UMLDesigner_v9-win32.win32.x86_64.zip
                type: zip
                root_install_dir: D:\AppServ
                create_directory: no # Default: yes
                main_app_launcher: UMLDesigner.exe
                desktop_shortcut: yes # Default: no
                #startmenu_shortcut: yes # Default: yes


- name: "Setup Apache Maven"
  hosts: all
  gather_facts: no
  tags: maven
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: maven
        setup:
          - installations:
            - software_components:
              - software_fullname: "apache-maven-3.9.4" # /!\ Attention when 'create_directory' is set to 'no' /!\
                file_relative_url: maven/apache-maven-3.9.4-bin.zip
                type: zip
                root_install_dir: D:\AppServ
                create_directory: no # Default: yes
                desktop_shortcut: no # Default: no
                startmenu_shortcut: no # Default: yes
        post_setup:
          - configurations:
            - update_resource:
              - resource_type: env_var
                resource_name: PATH
                value: D:\AppServ\apache-maven-3.9.4\bin
                action: append


- name: "Setup Python 2"
  hosts: all
  gather_facts: no
  tags: python2
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: python2
        pre_setup:
          - configurations:
            - update_resource:
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python2/python-2.7.18.amd64-pdb.zip
                destination: D:\AppServ\python2\Symbols
                unzip: yes
                skip_if_path_exists: D:\AppServ\python2\Symbols
        setup:
          - installations:
            - software_components:
              - software_fullname: Python 2.7.18 (64-bit)
                file_relative_url: python2/python-2.7.18.amd64.msi
                type: msi
                root_install_dir: D:\AppServ
                install_directory_name: python2
                #additional_arguments: ALLUSERS=1 ADDLOCAL=ALL
                additional_arguments: ALLUSERS=1 ADDLOCAL=DefaultFeature,TclTk,Documentation,Tools,pip_feature,Testsuite
                #abort_on_aftercheck_failure: no # Default: yes


- name: "Setup Python 3.12"
  hosts: all
  gather_facts: no
  tags: python312
  roles:
    - role: ans-win-auto-prov
      vars:
        shortname: python312
        pre_setup:
          - configurations:
            - update_resource:
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/core_pdb.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/core_d.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/exe_pdb.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/exe_d.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/dev_d.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/lib_pdb.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/lib_d.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/test_pdb.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/test_d.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/tcltk_pdb.msi
                destination: "{{ win_temp_dir_path }}"
              - resource_type: file_system
                operation_type: transfer
                source:
                  file_relative_url: python312/tcltk_d.msi
                destination: "{{ win_temp_dir_path }}"
        setup:
          - installations:
            - software_components:
              - software_fullname: "Python 3.12.0"
                file_relative_url: python312/python-3.12.0-amd64.exe
                type: exe
                arguments: /quiet InstallAllUsers=1 TargetDir=D:\AppServ\Python312 PrependPath=0 AppendPath=0 AssociateFiles=0 Include_symbols=1 Include_debug=1
                root_install_dir: D:\AppServ\Python312

        post_setup:
          - configurations:
            - update_resource:
              - resource_type: file_system
                operation_type: transfer
                source:
                  upload_file: bundles/basic_win/setup-python312/check_PYTHON_paths.ps1
                destination: C:\opt\ScriptPS\Starter\startup_scripts\

              - resource_type: file_system
                operation_type: transfer
                source:
                  upload_file: bundles/basic_win/setup-python312/set_PYTHON_paths.ps1
                destination: D:\AppServ\Python312\

              - resource_type: file_system
                operation_type: shortcut
                source: '%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe'
                arguments: '-WindowStyle Hidden -ExecutionPolicy Bypass -File "D:\AppServ\Python312\set_PYTHON_paths.ps1"'
                destination: '%PUBLIC%\Desktop\Set Runtime Versions\Set Python Version.lnk'
                icon: D:\AppServ\Python2\python.exe,0

  #tasks:
  #  - name: '[POST-SETUP] {PYTHON312} Notify logged in users with a message'
  #    community.windows.win_msg:
  #      display_seconds: 259200
  #      msg: "** SYSTEM ADMIN ** \n\nPython configurations updated. Please, save your work and log off (sign out) to enable them."
  #    changed_when: false
  #    no_log: yes
