---
# ansible-playbook main.yml -i ../inventories/environments/dev.yml

#- name: "Gather and display all facts"
#  hosts: all
#  tags: gatherfacts
#  tasks:
#    - name: "Gather all facts
#      setup:
#    - name: "Display all gathered facts
#      debug:
#        var: ansible_facts

#- name: "Show all variables"
#  hosts: all
#  tags: gatherfacts
#  tasks:
#    - name: Show all variables
#      ansible.builtin.debug: msg="{{ lookup('ansible.builtin.varnames', '.+')}}"

#https://nodejs.org/dist/v14.17.3/node-v14.17.3-x64.msi

#- name: Setup Node.JS versions 14, 16 and 18
#  hosts: all
#  gather_facts: no
#  tags: nodejs
#  roles:
#    - role: setup-nodejs
#      vars:
#        pre_setup:
#          installations:
#            software_components:
#              - software_fullname: "nvm-windows"
#                file_relative_url: nodejs/nvm-noinstall.zip
#                type: zip
#                root_install_dir: D:\AppServ
#                startmenu_shortcut: no # Default: yes
#          configurations:
#            update_resource:
#              - resource_type: env_var
#                resource_name: NVM_HOME
#                value: D:\AppServ\nvm-windows
#                action: create
#                abort_on_failure: yes # Default: 'no'
#              - resource_type: env_var
#                resource_name: NVM_SYMLINK
#                value: D:\AppServ\nvm_windows\nodejs_symlinks
#                action: create
#                abort_on_failure: yes # Default: 'no'
#              - resource_type: env_var
#                resource_name: PATH
#                value: '%NVM_HOME%;%NVM_SYMLINK%'
#                action: append
#                abort_on_failure: yes # Default: 'no'

# ...
- name: Setup Node.JS versions 14, 16 and 18
  hosts: all
  gather_facts: no
  tags: nodejs
  roles:
    - role: setup-nodejs
      vars:
        pre_setup:
          - executions:
            - run_ps1_script:
              - file_relative_url: ms-office-16/scripts/ms-office-kms-activate.ps1
                #http_auth_username: john          # These override (only for this 'executionsrun_ps1_script' job) 
                #http_auth_password: p@ssw0rd      # any globally-defined HTTP auth. credentials
                arguments: "kms.server.local"
                #working_directory: C:\temp\my office stuff\misc
                abort_on_failure: yes # Default: 'no'
          - installations:
            - software_components:
              - software_fullname: "nvm-windows" 
                file_relative_url: nodejs/nvm-noinstall.zip
                type: zip
                root_install_dir: D:\AppServ
          - checks:
            - check_net_flows:
              - target_host: kms.server.local
                target_port: 1688
                #abort_on_failure: yes # Default: 'no'
        setup:
          - installations:
            - software_components:
              - software_fullname: "Sysinternals Suite" 
                #file_relative_url: sysinternals/SysinternalsSuite.zip
                file_relative_url: sysinternals/SysinternalsSuite.zip
                type: zip
                root_install_dir: D:\AppServ
                desktop_shortcut: yes # Default: no
                #startmenu_shortcut: no # Default: yes
        post_setup:
          - configurations:
            - update_resource:
              - resource_type: env_var
                resource_name: PATH
                value: D:\AppServ\OpenSSL-Win64\bin
                action: append # [create, modify, delete] # Default behaviour: attempts 'create' action
                #abort_on_failure: yes # Default: 'no'


